### ISSUE TITLE
Community operator fails install in OKD-4.10

### ISSUE THREAD

**Issue by hy-tomas-terala** [openshift/windows-machine-config-operator#1177]
Tried installing operator from the operator hub in an OKD cluster on vSphere. Used all default values and checked the box for 'Enable Operator recommended cluster monitoring on this Namespace'. Install was waiting for a long time and sometimes flashed the following message:

InstallWaiting: installing: waiting for deployment windows-machine-config-operator to become ready: deployment "windows-machine-config-operator" not available: Deployment does not have minimum availability.

After a while the install failed with the following text: 

Failed: install failed: deployment windows-machine-config-operator not ready before timeout: deployment "windows-machine-config-operator" exceeded its progress deadline

Tried doing the install again multiple times with similar results each time.

More OKD info:
OpenShift version      4.10.0-0.okd-2022-07-09-073606
Kubernetes version    v1.23.5-rc.0.2076+8cfebb1ce4a59f-dirty
Channel                      stable-4

**Comment by hy-tomas-terala** [comment]
Below the csv file for the install

[clusterserviceversion-community-windows-machine-config-operator.v5.1.2.txt](https://github.com/openshift/windows-machine-config-operator/files/9316475/clusterserviceversion-community-windows-machine-config-operator.v5.1.2.txt)

**Comment by sebsoto** [comment]
@hy-tomas-terala 
There should be a `windows-machine-config-operator-*` pod failing to deploy in the namespace  `openshift-windows-machine-config-operator`.
Can you share the logs for that pod? It should explain why the deployment is failing.

**Comment by hy-tomas-terala** [comment]
[logs-windows-machine-config-operator-*.txt](https://github.com/openshift/windows-machine-config-operator/files/9316576/logs-windows-machine-config-operator-.txt)

Hope this helps, somehow I only got these logs by not checking the box for 'Enable Operator recommended cluster monitoring on this Namespace'

**Comment by sebsoto** [comment]
Thanks, the issue is your cluster uses `OpenShiftSDN` networking.
Your cluster needs to be set up with hybrid OVN networking in order to use this operator.
More information [here](https://github.com/openshift/windows-machine-config-operator/blob/master/docs/wmco-prerequisites.md#supported-networking).

Unfortunately I don't think there is an easy way to transition from one network setup to another yet, so all I can recommend is trying the operator on a fresh cluster, while following [these steps](https://github.com/openshift/windows-machine-config-operator/blob/master/docs/setup-hybrid-OVNKubernetes-cluster.md)

**Comment by hy-tomas-terala** [comment]
Thank you Sebastian for your help! Since this issue is on our end, I'm closing the issue.
