### ISSUE TITLE
Feature request: Support airgapped setup on vSphere, make pause image location configurable/prepull pause image

### ISSUE THREAD

**Issue by jomeier** [openshift/windows-machine-config-operator#579]
Hi,

as of https://github.com/openshift/windows-machine-config-operator/issues/141#issuecomment-887574152

the only reason, why airgapped OCP installations with Windows Containers are not supported seems to be that the pause image must be pulled from the internet.

Because we must provide our customers support for Windows Containers in production we are definitely interested to get support for this from RH.

An idea to mitigate this problem (as we did it in our own OCP Windows container test setup):
* we prepared a golden Windows VM as described in the documentation (with modifications we had to reverse engineer because the docs are not complete) in an environment where we had internet access
* we prepulled the pause image from the internet to the golden Windows VM
* we sysprepped the golden Windows VM
* we created the MachineSet for vSphere using the previously configured golden Windows VM in our airgapped cluster

In our setup everything works great with Windows containers, no problems in our airgapped environment.

The second option would be to make the hard coded pause image configurable (environment variable of WMCO operator?) so OCP users can store the pause image in an airgapped registry on premises. This should also be rather simple.

In our opinion airgapped clusters are very convenient with OCP intalled on vSphere. So this feature definitely should be support or at least the workaround with prepulled pause images on the golden Windows VM should be supported.

Could you have a look on that, please? It's very important for us.

Thanks and greetings,

Josef

**Comment by saifshaikh48** [comment]
There does not seem to be any problems to me in the workaround you have tried and outlined. Glad to hear Windows containers ran without issue.

Air-gapped environment support is still something that is not officially supported, until we fully test and add documentation around it ourselves. I have created a few stories ([WINC-662](https://issues.redhat.com/browse/WINC-662) & [WINC-663](https://issues.redhat.com/browse/WINC-663)) to put this work on our radar; the team will work to prioritize these soon.

**Comment by jomeier** [comment]
@saifshaikh48 
@aravindhp 
Thank you !

@philipp1992
Could you provide the unattend.xml we used to create the initial setup of the workers and the steps we provided to create the golden image, please?

**Comment by philipp1992** [comment]
> @philipp1992
> Could you provide the unattend.xml we used to create the initial setup of the workers and the steps we provided to create the golden image, please?

we used the unattend.xml provided in the docs minus the product-key section

https://docs.openshift.com/container-platform/4.8/windows_containers/creating_windows_machinesets/creating-windows-machineset-vsphere.html#creating-the-vsphere-windows-vm-golden-image_creating-windows-machineset-vsphere


by the way, since we are talking about the documentation and golden image, we found many errors within this documentation.

1: Install-Module -Force OpenSSHUtils -> this module is deprecated and can't be installed as described. also its not needed anymore

2: the way the ssh authorized_keys is supposed to be placed in the Administrators homedir does not work at all, because the users homedir will be wiped by sysprep. the docs mention, that this should be prevented by the provided unattend.xml, but there is no such mechanism in the xml. so we had to put the authorized_keys files outside of the homedir and modify the sshd_config accordingly. 
this behaviour was also reported months ago in this issue: https://github.com/openshift/windows-machine-config-operator/issues/484

3: another thing that bothers me is, that the provided unattend.xml enabled auto-logon. this means anyone with console access to the vm can access the operating system without logging in first. useful for troubleshooting not so nice security wise. Can you please explain, if this is really needed?

**Comment by aravindhp** [comment]
@jrvaldes please address @philipp1992's questions regarding the golden image creation process.

**Comment by jrvaldes** [comment]
Dear @philipp1992, thanks for sharing your notes; there is an ongoing effort to correct the documentation around the golden image creation process, please refer to [c8ff886](https://github.com/openshift/windows-machine-config-operator/commit/c8ff886a27213d6d77f709fc741cac3cb42a21ee) and [48fbd2e](https://github.com/openshift/windows-machine-config-operator/commit/48fbd2e8dd1fd6363bde271dfd8bcab0c327d76a).

>1: Install-Module -Force OpenSSHUtils -> this module is deprecated and can't be installed as described. also its not needed anymore

Corrected in [Set up SSH](https://github.com/openshift/windows-machine-config-operator/blob/master/docs/vsphere-golden-image.md#3-set-up-ssh) section.

>2: the way the ssh authorized_keys is supposed to be placed in the Administrators homedir does not work at all, because the users homedir will be wiped by sysprep. the docs mention, that this should be prevented by the provided unattend.xml, but there is no such mechanism in the xml. so we had to put the authorized_keys files outside of the homedir and modify the sshd_config accordingly.
this behaviour was also reported months ago in this issue: #484

Corrected in [Deploying the public key](https://github.com/openshift/windows-machine-config-operator/blob/master/docs/vsphere-golden-image.md#deploying-the-public-key) section.

>3: another thing that bothers me is, that the provided unattend.xml enabled auto-logon. this means anyone with console access to the vm can access the operating system without logging in first. useful for troubleshooting not so nice security wise. Can you please explain, if this is really needed?

That's a good question and yes it's a security risk to leave an Administrator' terminal open. I need to run few more tests to identify if is "really needed". However, to mitigate this, you can tune the [LogonCount](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-autologon-logoncount#values) value to specify the number of times that you can log on to the computer by using AutoLogon. Be aware of the [LogonCount known issue](https://docs.microsoft.com/en-us/windows-hardware/customize/desktop/unattend/microsoft-windows-shell-setup-autologon-logoncount#logoncount-known-issue).

>4: also the ssh key pair didn't work, when creating it on linux with ssh-keygen, so I had to create it on the windows machine with the same command and use the private key from the windows machine for the operator secret. didn't further investigate into this.

Glad you found a workaround to this issue. can you provide a set of instructions to replicate it? Looks like need further investigation in a separate issue, since is not related with the golden image creation process.

**Comment by jrvaldes** [comment]
@jomeier, @philipp1992

>3: another thing that bothers me is, that the provided unattend.xml enabled auto-logon. this means anyone with console access to the vm can access the operating system without logging in first. useful for troubleshooting not so nice security wise. Can you please explain, if this is really needed?

As a follow-up see https://github.com/openshift/windows-machine-config-operator/pull/515/commits/90d680d529aa57c2585b9a641d1d80e5d0324399, you're right the `AutoLogon` feature is not needed. Thanks for calling it out.
